### ISSUE TITLE
Meaning of ***

### ISSUE THREAD

**Issue by fxfactorial** [DavidGoldman/InspectiveC#13]
Great tool, thanks.

I'm wondering what lines like 

```
***-|Some object<some_address> cy$hasProperty:| @"toCYON"***
```
mean

**Comment by DavidGoldman** [comment]
This occurs when the given object/class/selector for the line is being watched. So if you do `watchObject(obj);` you will see something like `***-|Class<obj's address> method|***`.

**Comment by fxfactorial** [comment]
@DavidGoldman Thanks, but I don't see methods of interest, mostly retain/release/class and I get ` cy$hasProperty:| @"toCYON"***` for some of them. Does this likely mean I'm just targeting the wrong object?

**Comment by DavidGoldman** [comment]
That or maybe the methods aren't being called (or are being called on a different thread - by default it only tracks on the main thread).

**Comment by fxfactorial** [comment]
@DavidGoldman I see, being on a separate thread is most likely, probably a `dispatch_async` kind of thing, any way to have this work with those cases as well?

**Comment by DavidGoldman** [comment]
Clone, comment out [this](https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveC.mm#L16) line, compile and install on your device.

**Comment by fxfactorial** [comment]
@DavidGoldman Awesome! I will try and report back.

**Comment by fxfactorial** [comment]
@DavidGoldman Okay, getting 

```
_assert(CYRecvAll(client, &size, sizeof(size))):../Console.cpp(274):Run
```

after doing: 
```
intFunc=new Type("v").functionWith(int);objFunc=new Type("v").functionWith(id);classFunc=new Type("v").functionWith(Class);selFunc=new Type("v").functionWith(SEL);voidFunc=new Type("v").functionWith(new Type("v"));objSelFunc=new Type("v").functionWith(id,SEL);classSelFunc=new Type("v").functionWith(Class,SEL);handle=dlopen("/usr/lib/libinspectivec.dylib",RTLD_NOW);setMaximumRelativeLoggingDepth=intFunc(dlsym(handle,"InspectiveC_setMaximumRelativeLoggingDepth"));watchObject=objFunc(dlsym(handle,"InspectiveC_watchObject"));unwatchObject=objFunc(dlsym(handle,"InspectiveC_unwatchObject"));watchSelectorOnObject=objSelFunc(dlsym(handle,"InspectiveC_watchSelectorOnObject"));unwatchSelectorOnObject=objSelFunc(dlsym(handle,"InspectiveC_unwatchSelectorOnObject"));watchClass=classFunc(dlsym(handle,"InspectiveC_watchInstancesOfClass"));unwatchClass=classFunc(dlsym(handle,"InspectiveC_unwatchInstancesOfClass"));watchSelectorOnClass=classSelFunc(dlsym(handle,"InspectiveC_watchSelectorOnInstancesOfClass"));unwatchSelectorOnClass=classSelFunc(dlsym(handle,"InspectiveC_unwatchSelectorOnInstancesOfClass"));watchSelector=selFunc(dlsym(handle,"InspectiveC_watchSelector"));unwatchSelector=selFunc(dlsym(handle,"InspectiveC_unwatchSelector"));enableLogging=voidFunc(dlsym(handle,"InspectiveC_enableLogging"));disableLogging=voidFunc(dlsym(handle,"InspectiveC_disableLogging"));enableCompleteLogging=voidFunc(dlsym(handle,"InspectiveC_enableCompleteLogging"));disableCompleteLogging=voidFunc(dlsym(handle,"InspectiveC_disableCompleteLogging"))
``` 
in cycript

**Comment by DavidGoldman** [comment]
Are you sure inspectivec is loaded into the process?

**Comment by fxfactorial** [comment]
@DavidGoldman yea I am, it crashed the process on the main thread, 

here's relevant thread post `symbolicate`

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0     + libdispatch.dylib               0x35baaafc 0x35b84000 + 0x26afc         // 0x000234d4 + 0x3628
1       ???                             0x00000000 0x00000000 + 0x0     
2       ???                             0x38a5a880 0x00000000 + 0x38a5a880
3       ???                             0x38a5ab4c 0x00000000 + 0x38a5ab4c
```

goes on and on like that.

**Comment by DavidGoldman** [comment]
How are you building InspectiveC? Try building it with the iOS 8.4 SDK or if you're using the new version of theos, try building with `FOR_RELEASE=1` or `FINALPACKAGE=1`.

**Comment by fxfactorial** [comment]
I am building it on Linux using a cross compiler that I packaged, built against iOS9.2. (http://hyegar.com/2016/02/22/ios-cross-compiler/)  and using `FINALPACKAGE=1`

**Comment by DavidGoldman** [comment]
Hmm, try using the iOS 8.4 SDK, someone previously reported that doing so helped. If you built it without that line commented out, does it still crash?

**Comment by fxfactorial** [comment]
@DavidGoldman rebuilding with the 8.4 SDK will be take me longer than just now and i need this to run on iOS 9. 
Tried without commenting out the `#define` but still crashes.

**Comment by DavidGoldman** [comment]
Hmm, try [this](https://dl.dropboxusercontent.com/u/60272173/com.golddavid.inspectivec_1.0.9-9_iphoneos-arm.deb) version. Still crash?

**Comment by fxfactorial** [comment]
@DavidGoldman Yes!! That worked, thank you so much!!
