### ISSUE TITLE
Example no longer functional

### ISSUE THREAD

**Issue by ZaneH** [DavidGoldman/InspectiveC#15]
The example project in the repository doesn't seem to be functional anymore.
I can't seem to get any of the actual options in the README to work either.

iPhone 5S iOS 10.2 - Yalu102

**Comment by DavidGoldman** [comment]
Are you having issues compiling or getting it to work? Currently it's not working on iOS 10 - I'll make a separate issue for that.

**Comment by ZaneH** [comment]
I was just having troubles getting it to work. All my logs were blank and the process crashed 100% of the time.
But, it looks like you already know about it. I guess we'll just have to sit tight!

**Comment by DavidGoldman** [comment]
Closing as this is a duplicate of #16.
