### ISSUE TITLE
after init, no response.

### ISSUE THREAD

**Issue by jmpews** [DavidGoldman/InspectiveC#18]
if i use file to init, it will no response

```
jmpewsde-iPhone:/private/var/mobile/Documents/Dumped root# cycript -p PUClient InspectiveC.cy

```

if i use line commnd, it will so slow that to response.

and i just can force to stop the process.

**Comment by jmpews** [comment]
or just return.

```
jmpewsde-iPhone:/private/var/mobile/Documents/Dumped root# cycript -p DidEPTool InspectiveC.cy
jmpewsde-iPhone:/private/var/mobile/Documents/Dumped root#
```

**Comment by DavidGoldman** [comment]
Are you on iOS 10? (see #16) - if so, it's not working on iOS 10 as of yet.

Note that cycript is supposed to exit (just not crash) after loading the .cy file - that's working as intended.

Also try changing [InspectiveC.cy:5](https://github.com/DavidGoldman/InspectiveC/blob/master/cycript/InspectiveC.cy#L5) to `var voidFunc = @encode(void(void));` and let me know if that helps for the command.

**Comment by jmpews** [comment]
wow, i use the 'command line' in readme.md before, not working,  but now use the command line with `InspectiveC.compiled.cy` and work fine.

but the log file so so big, it take me such a while to download 2 my local mac. 😂

i think of some optimization methods, so if code done i will pull request.

btw: the project code is so nice,  In particular, the data structure.

```
struct RegState_ {
  union {
    uint64_t arr[10];
    struct {
      uint64_t x0;
      uint64_t x1;
      uint64_t x2;
      uint64_t x3;
      uint64_t x4;
      uint64_t x5;
      uint64_t x6;
      uint64_t x7;
      uint64_t x8;
      uint64_t lr;
    } regs;
  } general;

  union {
    FPReg arr[8];
    struct {
      FPReg q0;
      FPReg q1;
      FPReg q2;
      FPReg q3;
      FPReg q4;
      FPReg q5;
      FPReg q6;
      FPReg q7;
    } regs;
  } floating;
};

typedef struct pa_list_ {
  struct RegState_ *regs; // Registers saved when function is called.
  unsigned char *stack; // Address of current argument.
  int ngrn; // The Next General-purpose Register Number.
  int nsrn; // The Next SIMD and Floating-point Register Number.
} pa_list;
```
thanks for your code.

**Comment by DavidGoldman** [comment]
Yeah, the log files can definitely get too big. Feel free to submit a PR!
