### ISSUE TITLE
fatal error: error in backend: misaligned ARM call destination

### ISSUE THREAD

**Issue by rozbo** [DavidGoldman/InspectiveC#20]
at first, I download ur repo's newest deb for my iphone5 on ios8, but it crash anyway.
so I clone your repo and build it by `theos` with xcode8 and 9.2 sdk  ,then I found a 

```
fatal error: error in backend: misaligned ARM call destination
```
it just cause by `armv7`, `arm64` is fine, but my iphone is armv7....

I find the reason is 
```oc
"blx __Z19getOrigObjc_msgSendv\n"
```

```oc
uintptr_t getOrigObjc_msgSend() {
  return reinterpret_cast<uintptr_t>(orig_objc_msgSend);
}
```

But it is ashamed that I I can't fix it....

anyway?
thanks!!!

**Comment by kezax94** [comment]
encountered the same, adding -fsanitize=alignment to compiler flags solved it.

**Comment by rozbo** [comment]
@kezax94 I will try it, and thank you very much

**Comment by kezax94** [comment]
@rozbo you can set it for the particular file which generates the error, in Build Phases/Compile Sources, right column :)
