### ISSUE TITLE
No logs created for apsd daemon

### ISSUE THREAD

**Issue by mbazaliy** [DavidGoldman/InspectiveC#6]
Steps to reproduce:

1. Link tweak agains inspectivec.dylib
2. Tweak code:
```xml
#import "InspectiveC.h"
%ctor {
	NSLog(@"[LOGGGGGERRR] --- >>> Entry point <<< ---");
     InspectiveC_setMaximumRelativeLoggingDepth(5);
//	 InspectiveC_enableCompleteLogging();
	 InspectiveC_enableLogging();
	}
```
tweak.plist filter:
```xml
{
	Filter = {
		Executables = (
			apsd,
		);
	};
}
```
4. [InspectiveC] Loading - Directory is "/var/mobile/Documents"
5. No logs created

**Comment by DavidGoldman** [comment]
It's also logging the "[LOGGGGGERRR] --- >>> Entry point <<< ---" from the apsd process, right? 

Does the "/var/mobile/Documents/" directory exist? If it doesn't, it won't create it. Otherwise it may be a permission issue.

**Comment by mbazaliy** [comment]
>It's also logging the "[LOGGGGGERRR] --- >>> Entry point <<< ---" from the apsd process, right?
Yes, it is from apsd process.

"/var/mobile/Documents/" exist.

I have tried with other daemons like itunesstored - it works fine and save logs in "/var/mobile/Documents/"

**Comment by DavidGoldman** [comment]
Try logging the retval of https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveC.mm#L311 alongside errno, it's probably a permission issue.

**Comment by mbazaliy** [comment]
I have added some logging code:

```xml
  errno = 0 ;
    FILE * tmp;
    if((tmp=fopen(path,"a"))==NULL)
    {
        NSLog(@"could not open file");
        NSLog(@"Error = %s", strerror(errno));
    }
```

**Comment by DavidGoldman** [comment]
ESRCH is a very odd error for fopen - probably a sandbox issue. You could try changing the directory at https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveC.mm#L544.

**Comment by mbazaliy** [comment]
According to this - http://iphonedevwiki.net/index.php/Seatbelt - "The filesystem cannot be accessed at all."

I was trying to change entitlements for apsd daemon and now looks like my device run in infinite loop :) I will update this thread when I fix it and patch entitlements.

As a result of comment above, could you add an option to dump results in console, instead of file (maybe it is not a good idea, according to log sizes)

**Comment by DavidGoldman** [comment]
Where would you want it to log to? stdout or just NSLog?

**Comment by mbazaliy** [comment]
syslog(NSLog) will be fine

**Comment by DavidGoldman** [comment]
Logging to the syslog using NSLog will be fairly annoying as you'd have to get everything logged in one call and all current methods use a FILE *. Don't think there's a good solution for it sadly, but you're free to fork the project and modify it to work.

Maybe you can get the entitlements changed? Not exactly sure how, but it *should* be possible.

**Comment by mbazaliy** [comment]
Ok, I have patched entitlements in a proper way and logging works :)

Thanks for your help, and thanks for creating such great instrument. Closing issue now.

**Comment by DavidGoldman** [comment]
Mind if I ask how you fixed the entitlements?

**Comment by mbazaliy** [comment]
I dump an original entitlements with codeisgn and resign daemon with fixed entitlements
