### ISSUE TITLE
Feature request: logging caller image name

### ISSUE THREAD

**Issue by mbazaliy** [DavidGoldman/InspectiveC#7]
It could be really great to know who is calling particular objc_msgSend. Could you add a caller image name to logfile ?

Something like:
```xml
 void *addr = __builtin_return_address(0);
 Dl_info info;
 dladdr(addr, &info);
 NSString *callerName = [NSString stringWithUTF8String: info.dli_sname]; // thats bad and just an example
```

**Comment by DavidGoldman** [comment]
This can easily be added to preObjc_msgSend since the lr argument is the return address. 

However, how would the image name fit in with the current logging format?

**Comment by mbazaliy** [comment]
When should I add a code to not corrupt a stack ? I see a + 208 const for arm64 for example.

What if
```xml
|Foundation| -|NSPlaceholderString@<0x12f60c520> initWithFormat:| @"/var/mobile/Library/Preferences/%@"
```

**Comment by DavidGoldman** [comment]
[On stack corruption](https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveCarm64.mm#L18): 208 is the offset from the regstate to the top of the stack when objc_msgSend was called (where arguments may be ). Notice 208 == sizeof(struct RegState_). As long as you don't mess with the regstate struct you'll be fine.

Not sure if I'm a fan of that - won't it mess up the indentation?

**Comment by mbazaliy** [comment]
I've add this code to preObjc_msgSend

```xml
  Dl_info info;
    if(dladdr((void*)lr, &info) != 0 ) {
        fprintf(cs->file, "|%s| ", strrchr(info.dli_fname, '/')+1);
    }
```

and now its looks like this:
```xml
|libinspectivec.dylib|     +|NSArray allocWithZone:| NULL
|CoreFoundation|       +|NSArray self|
|CoreFoundation|       +|__NSPlaceholderArray immutablePlaceholder|
|CoreFoundation|   -|__NSArrayM@<0x17004e7f0> count|
|CoreFoundation|   -|__NSPlaceholderArray@<0x17400be90> initWithArray:range:copyItems:| <__NSArrayM@0x17004e7f0> {0, 1} false
```

**Comment by DavidGoldman** [comment]
Ah, it shouldn't be added to preObjc_msgSend. The problem is that when logging [happens](https://github.com/DavidGoldman/InspectiveC/blob/master/InspectiveC.mm#L436), [obj class] is called to make sure the class is initialized, which can lead to a [<classObj> initialize] call.

**Comment by mbazaliy** [comment]
Hm, what is a good place to put it instead of preObjc_msgSend ?

**Comment by DavidGoldman** [comment]
I would modify onWatchHit and onNestedCall to pass curRecord.lr to logWatchedHit and logObjectAndArgs, which they can use for dladdr.

**Comment by mbazaliy** [comment]
Thanks for update, just implemented it. Sometimes I see stuff like this:
```xml
|libinspectivec.dylib| -|UIStatusBarDataNetworkItemView@<0x13de16c70> _resizeWithOldSuperviewSize:| {0, 20} 
```
or this 
```xml
|BaseBoard| -|FBSDisplay@<0x1740589f0> isKindOfClass:| [FBSDisplay class]
|libobjc.A.dylib| -|FBSDisplay@<0x1740589f0> class|  -- ?
|FrontBoardServices| -|FBSDisplay@<0x1740589f0> caDisplay|
```

Looks like some image names were resolved incorrectly. Other problem - performance is not good with image name logging.

**Comment by DavidGoldman** [comment]
I'm not sure how good dladdr is, but what you're seeing may be due to tail call optimizations.

You could also try caching the result from dladdr - that may improve performance.

**Comment by mbazaliy** [comment]
I think I can close this now, thanks for your help.

**Comment by DavidGoldman** [comment]
No problem.
